trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: build_and_deploy_app_demo
  displayName: 'Build and Deploy App Demo'
  steps:
  
  - checkout: self
    displayName: '🧾 Checkout repo'

  - task: UsePythonVersion@0
    displayName: '🐍 Setup Python'
    inputs:
      versionSpec: '3.10'
      addToPath: true

  - script: |
      echo "Installing dependencies..."
      # python -m pip install --upgrade pip
      # pip install -r requirements.txt
    workingDirectory: ./02-environment/sentiment_analysis
    displayName: '📦 Install dependencies'

  - script: |
      echo "Building Docker image..."
      # docker build -t myapp:latest .
    workingDirectory: ./04-docker/example
    displayName: '🛠️ Build Docker image'

  - script: |
      echo "Pushing Docker image..."
      # docker login
      # docker push myregistry/myapp:latest
    workingDirectory: ./04-docker/example
    displayName: '🐳 Push Docker image'

  - script: echo "Deploying myapp:latest to PROD..."
    displayName: '🚀 Deploy to production'
