name: Build & Deploy MkDocs

on:
  push:
    branches:
        - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      working-directory: ./docs_config
      run: |
        pip install -r requirements.txt

    - name: Deploy 🚀
      working-directory: ./docs_config
      run: |
        mkdocs gh-deploy --force
